AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: P1

Resources:
  A3b1website:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "frontend-assign02"

  A3b2photostore:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "assign02-photos" 

  A3L0:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: search-photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./LF0
      Description: search-photos
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::941405448767:role/service-role/search-photos-role-2vnnxbif'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /search-images
            Method: post
      Environment:
        Variables:
          REGION: us-east-1

  A3L1:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: index-photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./LF1
      Description: index-photos
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::941405448767:role/service-role/index-photos-role-ye3i64cc'
      Environment:
        Variables:
          REGION: us-east-1

  A3L2:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: upload_to_s3
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./lambda_function_3.py
      Description: upload_to_s3
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::098015424271:role/service-role/upload_to_s3-role-9x78khho'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /upload-image-s3-lambda
            Method: post
      Environment:
        Variables:
          REGION: us-east-1
      
  ElasticsearchDomain:
    Type: 'AWS::Elasticsearch::Domain'
    Properties:
      DomainName: "photos"
      ElasticsearchVersion: '7.10'
      ElasticsearchClusterConfig:
        DedicatedMasterEnabled: 'false'
        InstanceCount: '2'
        ZoneAwarenessEnabled: 'true'
        InstanceType: "t2.small.elasticsearch"
      EBSOptions:
        EBSEnabled: true
        Iops: 0
        VolumeSize: 10
        VolumeType: "gp2"
      SnapshotOptions:
        AutomatedSnapshotStartHour: '0'
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: 'arn:aws:es:us-east-1:941405448767:domain/photos/*'
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: "true"